### ISSUE TITLE
Log file not being auto created

### ISSUE THREAD

**Issue by JosephTico** [Linus2punkt0/bluesky-crossposter#40]
Looks like the log files are not being created by the program

```python
Traceback (most recent call last):
  File "/home/joseph/bluesky-crossposter/crosspost.py", line 542, in <module>
    posts = getPosts()
  File "/home/joseph/bluesky-crossposter/crosspost.py", line 37, in getPosts
    writeLog("Gathering posts")
  File "/home/joseph/bluesky-crossposter/crosspost.py", line 479, in writeLog
    dst = open(log, append_write)
FileNotFoundError: [Errno 2] No such file or directory: '/logs/231019.log'
```

**Comment by Linus2punkt0** [comment]
The log files are autocreated as long as the folder exists. It looks like your base path is set to /, which means it's looking for the logs folder in the root of your file system. It needs to be set to the folder where the poster is actually located.
