### ISSUE TITLE
Errors out of gathering posts when a video post is present on BlueSky.

### ISSUE THREAD

**Issue by barberio** [Linus2punkt0/bluesky-crossposter#56]
This seems to entirely block gathering posts, as it errors out entirely if it finds a "app.bsky.embed.video#view" field.

```
crossposter-1  | Traceback (most recent call last):
crossposter-1  |   File "//crosspost.py", line 13, in <module>
crossposter-1  |     posts = get_posts(timelimit)
crossposter-1  |             ^^^^^^^^^^^^^^^^^^^^
crossposter-1  |   File "/input/bluesky.py", line 21, in get_posts
crossposter-1  |     profile_feed = bsky.app.bsky.feed.get_author_feed({'actor': BSKY_HANDLE})
crossposter-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
crossposter-1  |   File "/usr/local/lib/python3.12/site-packages/atproto_client/namespaces/sync_ns.py", line 292, in get_author_feed
crossposter-1  |     return get_response_model(response, models.AppBskyFeedGetAuthorFeed.Response)
crossposter-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
crossposter-1  |   File "/usr/local/lib/python3.12/site-packages/atproto_client/models/utils.py", line 101, in get_response_model
crossposter-1  |     return get_or_create(response.content, model)
crossposter-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
crossposter-1  |   File "/usr/local/lib/python3.12/site-packages/atproto_client/models/utils.py", line 67, in get_or_create
crossposter-1  |     raise e
crossposter-1  |   File "/usr/local/lib/python3.12/site-packages/atproto_client/models/utils.py", line 60, in get_or_create
crossposter-1  |     model_instance = _get_or_create(model_data, model, strict=strict)
crossposter-1  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
crossposter-1  |   File "/usr/local/lib/python3.12/site-packages/atproto_client/models/utils.py", line 92, in _get_or_create
crossposter-1  |     raise ModelError(str(e)) from e
crossposter-1  | atproto_client.exceptions.ModelError: 44 validation errors for Response
crossposter-1  | feed.28.reply.parent.function-after[__alert_about_extra_fields(), PostView].embed.function-after[__alert_about_extra_fields(), View].images
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...t': 1284, 'width': 720}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.28.reply.parent.function-after[__alert_about_extra_fields(), PostView].embed.function-after[__alert_about_extra_fields(), View].$type
crossposter-1  |   Input should be 'app.bsky.embed.images#view' [type=literal_error, input_value='app.bsky.embed.video#view', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
crossposter-1  | feed.28.reply.parent.function-after[__alert_about_extra_fields(), PostView].embed.function-after[__alert_about_extra_fields(), View].external
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...t': 1284, 'width': 720}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.28.reply.parent.function-after[__alert_about_extra_fields(), PostView].embed.function-after[__alert_about_extra_fields(), View].$type
crossposter-1  |   Input should be 'app.bsky.embed.external#view' [type=literal_error, input_value='app.bsky.embed.video#view', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
crossposter-1  | feed.28.reply.parent.function-after[__alert_about_extra_fields(), PostView].embed.function-after[__alert_about_extra_fields(), View].record
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...t': 1284, 'width': 720}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.28.reply.parent.function-after[__alert_about_extra_fields(), PostView].embed.function-after[__alert_about_extra_fields(), View].$type
crossposter-1  |   Input should be 'app.bsky.embed.record#view' [type=literal_error, input_value='app.bsky.embed.video#view', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
crossposter-1  | feed.28.reply.parent.function-after[__alert_about_extra_fields(), PostView].embed.function-after[__alert_about_extra_fields(), View].media
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...t': 1284, 'width': 720}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.28.reply.parent.function-after[__alert_about_extra_fields(), PostView].embed.function-after[__alert_about_extra_fields(), View].record
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...t': 1284, 'width': 720}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.28.reply.parent.function-after[__alert_about_extra_fields(), PostView].embed.function-after[__alert_about_extra_fields(), View].$type
crossposter-1  |   Input should be 'app.bsky.embed.recordWithMedia#view' [type=literal_error, input_value='app.bsky.embed.video#view', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
crossposter-1  | feed.28.reply.parent.function-after[__alert_about_extra_fields(), NotFoundPost].notFound
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.feed....': False}, 'labels': []}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.28.reply.parent.function-after[__alert_about_extra_fields(), NotFoundPost].$type
crossposter-1  |   Input should be 'app.bsky.feed.defs#notFoundPost' [type=literal_error, input_value='app.bsky.feed.defs#postView', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
crossposter-1  | feed.28.reply.parent.function-after[__alert_about_extra_fields(), BlockedPost].blocked
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.feed....': False}, 'labels': []}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.28.reply.parent.function-after[__alert_about_extra_fields(), BlockedPost].$type
crossposter-1  |   Input should be 'app.bsky.feed.defs#blockedPost' [type=literal_error, input_value='app.bsky.feed.defs#postView', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
crossposter-1  | feed.28.reply.root.function-after[__alert_about_extra_fields(), PostView].embed.function-after[__alert_about_extra_fields(), View].images
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...t': 1284, 'width': 720}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.28.reply.root.function-after[__alert_about_extra_fields(), PostView].embed.function-after[__alert_about_extra_fields(), View].$type
crossposter-1  |   Input should be 'app.bsky.embed.images#view' [type=literal_error, input_value='app.bsky.embed.video#view', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
crossposter-1  | feed.28.reply.root.function-after[__alert_about_extra_fields(), PostView].embed.function-after[__alert_about_extra_fields(), View].external
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...t': 1284, 'width': 720}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.28.reply.root.function-after[__alert_about_extra_fields(), PostView].embed.function-after[__alert_about_extra_fields(), View].$type
crossposter-1  |   Input should be 'app.bsky.embed.external#view' [type=literal_error, input_value='app.bsky.embed.video#view', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
crossposter-1  | feed.28.reply.root.function-after[__alert_about_extra_fields(), PostView].embed.function-after[__alert_about_extra_fields(), View].record
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...t': 1284, 'width': 720}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.28.reply.root.function-after[__alert_about_extra_fields(), PostView].embed.function-after[__alert_about_extra_fields(), View].$type
crossposter-1  |   Input should be 'app.bsky.embed.record#view' [type=literal_error, input_value='app.bsky.embed.video#view', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
crossposter-1  | feed.28.reply.root.function-after[__alert_about_extra_fields(), PostView].embed.function-after[__alert_about_extra_fields(), View].media
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...t': 1284, 'width': 720}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.28.reply.root.function-after[__alert_about_extra_fields(), PostView].embed.function-after[__alert_about_extra_fields(), View].record
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...t': 1284, 'width': 720}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.28.reply.root.function-after[__alert_about_extra_fields(), PostView].embed.function-after[__alert_about_extra_fields(), View].$type
crossposter-1  |   Input should be 'app.bsky.embed.recordWithMedia#view' [type=literal_error, input_value='app.bsky.embed.video#view', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
crossposter-1  | feed.28.reply.root.function-after[__alert_about_extra_fields(), NotFoundPost].notFound
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.feed....': False}, 'labels': []}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.28.reply.root.function-after[__alert_about_extra_fields(), NotFoundPost].$type
crossposter-1  |   Input should be 'app.bsky.feed.defs#notFoundPost' [type=literal_error, input_value='app.bsky.feed.defs#postView', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
crossposter-1  | feed.28.reply.root.function-after[__alert_about_extra_fields(), BlockedPost].blocked
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.feed....': False}, 'labels': []}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.28.reply.root.function-after[__alert_about_extra_fields(), BlockedPost].$type
crossposter-1  |   Input should be 'app.bsky.feed.defs#blockedPost' [type=literal_error, input_value='app.bsky.feed.defs#postView', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
crossposter-1  | feed.35.post.embed.function-after[__alert_about_extra_fields(), View].images
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...': 1920, 'width': 1080}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.35.post.embed.function-after[__alert_about_extra_fields(), View].$type
crossposter-1  |   Input should be 'app.bsky.embed.images#view' [type=literal_error, input_value='app.bsky.embed.video#view', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
crossposter-1  | feed.35.post.embed.function-after[__alert_about_extra_fields(), View].external
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...': 1920, 'width': 1080}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.35.post.embed.function-after[__alert_about_extra_fields(), View].$type
crossposter-1  |   Input should be 'app.bsky.embed.external#view' [type=literal_error, input_value='app.bsky.embed.video#view', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
crossposter-1  | feed.35.post.embed.function-after[__alert_about_extra_fields(), View].record
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...': 1920, 'width': 1080}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.35.post.embed.function-after[__alert_about_extra_fields(), View].$type
crossposter-1  |   Input should be 'app.bsky.embed.record#view' [type=literal_error, input_value='app.bsky.embed.video#view', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
crossposter-1  | feed.35.post.embed.function-after[__alert_about_extra_fields(), View].media
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...': 1920, 'width': 1080}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.35.post.embed.function-after[__alert_about_extra_fields(), View].record
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...': 1920, 'width': 1080}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.35.post.embed.function-after[__alert_about_extra_fields(), View].$type
crossposter-1  |   Input should be 'app.bsky.embed.recordWithMedia#view' [type=literal_error, input_value='app.bsky.embed.video#view', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
crossposter-1  | feed.47.post.embed.function-after[__alert_about_extra_fields(), View].images
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...t': 1280, 'width': 720}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.47.post.embed.function-after[__alert_about_extra_fields(), View].$type
crossposter-1  |   Input should be 'app.bsky.embed.images#view' [type=literal_error, input_value='app.bsky.embed.video#view', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
crossposter-1  | feed.47.post.embed.function-after[__alert_about_extra_fields(), View].external
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...t': 1280, 'width': 720}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.47.post.embed.function-after[__alert_about_extra_fields(), View].$type
crossposter-1  |   Input should be 'app.bsky.embed.external#view' [type=literal_error, input_value='app.bsky.embed.video#view', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
crossposter-1  | feed.47.post.embed.function-after[__alert_about_extra_fields(), View].record
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...t': 1280, 'width': 720}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.47.post.embed.function-after[__alert_about_extra_fields(), View].$type
crossposter-1  |   Input should be 'app.bsky.embed.record#view' [type=literal_error, input_value='app.bsky.embed.video#view', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
crossposter-1  | feed.47.post.embed.function-after[__alert_about_extra_fields(), View].media
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...t': 1280, 'width': 720}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.47.post.embed.function-after[__alert_about_extra_fields(), View].record
crossposter-1  |   Field required [type=missing, input_value={'$type': 'app.bsky.embed...t': 1280, 'width': 720}}, input_type=dict]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
crossposter-1  | feed.47.post.embed.function-after[__alert_about_extra_fields(), View].$type
crossposter-1  |   Input should be 'app.bsky.embed.recordWithMedia#view' [type=literal_error, input_value='app.bsky.embed.video#view', input_type=str]
crossposter-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error

```

**Comment by Linus2punkt0** [comment]
This issue is outside of the crossposter. Updating atproto should resolve it.

**Comment by Linus2punkt0** [comment]
Though I did just realize I have not added functionality for dealing with video posts, I will start working on this.

**Comment by barberio** [comment]
See pull request #57 which fixes the immediate bug

Updating atproto to 0.0.54 results in a compatibility problem that needs code updates around session handling.

```
crossposter-1  | Traceback (most recent call last):
crossposter-1  |   File "//crosspost.py", line 5, in <module>
crossposter-1  |     from input.bluesky import get_posts
crossposter-1  |   File "/input/bluesky.py", line 13, in <module>
crossposter-1  |     bsky.login(BSKY_HANDLE, BSKY_PASSWORD)
crossposter-1  |   File "/usr/local/lib/python3.12/site-packages/atproto_client/client/client.py", line 107, in login
crossposter-1  |     raise ValueError('Either session_string or login and password should be provided.')
crossposter-1  | ValueError: Either session_string or login and password should be provided.
```

**Comment by Linus2punkt0** [comment]
I'm not getting the same error running that version of atproto. Could either the password or username variable be empty?

**Comment by barberio** [comment]
I have both BSKY_HANDLE and BSKY_PASSWORD environment variables set in docker.

**Comment by Linus2punkt0** [comment]
Maybe they are not being imported properly? I'm not running in docker myself so I can't verify, but I am not getting that error when running that version either in WSL or on my server.

**Comment by Linus2punkt0** [comment]
Video handling has now been added to the beta branch, and will be merged into main soon. https://github.com/Linus2punkt0/bluesky-crossposter/tree/mk2.5-beta

**Comment by Linus2punkt0** [comment]
The fix has been merged, if issues persist, reopen this issue!
