### ISSUE TITLE
[BUG] Splitting posts to Twitter does not work

### ISSUE THREAD

**Issue by MedPlex98** [Linus2punkt0/bluesky-crossposter#70]
I have noticed that splitting the post into several tweets to Twitter does not work.
I get the following message:

```
2024-12-01 00:59:13 [DEBUG]: {'xxx': <Arrow [2024-12-01T00:40:16+01:00]>} (run crosspost.py:19)
2024-12-01 00:59:13 [DEBUG]: {'xxx': <Arrow [2024-12-01T00:40:16+01:00]>} (run crosspost.py:23)
2024-12-01 00:59:13 [INFO]: Splitting post that is too long for twitter. (split_post twitter.py:63)
2024-12-01 00:59:13 [ERROR]: Traceback (most recent call last):
  File "/home/container/output/post.py", line 115, in post
    tweet_id = tweet(post["text"], tweet_reply, tweet_quote, media, post["allowed_reply"])
  File "/home/container/output/twitter.py", line 38, in tweet
    post, partTwo = split_post(post)
  File "/home/container/output/twitter.py", line 71, in split_post
    first = "\n".join(sentences[:(len(sentences) - i)]) + "\n"
UnboundLocalError: local variable 'sentences' referenced before assignment
 (post post.py:118)
2024-12-01 00:59:13 [INFO]: Post xxx already sent to mastodon. (post post.py:132)
2024-12-01 00:59:13 [INFO]: Adding to database: {"skeet": "xxx", "ids": {"twitter_id": "", "mastodon_id": xxx}, "failed": {"twitter": 4, "mastodon": 0}} (db_write db.py:32)
2024-12-01 00:59:13 [INFO]: Saving post cache. (post_cache_write functions.py:166)
2024-12-01 00:59:13 [INFO]: Saving new database (save_db db.py:92)
2024-12-01 00:59:13 [INFO]: Deleting local images (cleanup functions.py:129)
```

I am currently on the Github version status of November 12th.

**Comment by Linus2punkt0** [comment]
Are you using the lastest version of the crossposter? Because I believe this should be a resolved issue!

**Comment by MedPlex98** [comment]
> Are you using the lastest version of the crossposter? Because I believe this should be a resolved issue!

The problem no longer exists, I pulled the latest data from Github.

Thank you very much!
